{%set name = "paramiko" %}
{%set version = "2.1.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "5fae49bed35e2e3d45c4f7b0db2d38b9ca626312d91119b3991d0ecf8125e310" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pycrypto >=2.1,!=2.4,<3.0
    - ecdsa >=0.11,<2.0

test:
  imports:
    - paramiko

about:
  home: http://www.paramiko.org/
  license: LGPL 2.1
  license_file: LICENSE
  summary: 'SSH2 protocol library'
  license_family: LGPL
  dev_url: https://github.com/paramiko/paramiko/
  doc_url: http://docs.paramiko.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - vamega
    - jakirkham
