{%set name = "paramiko" %}
{%set version = "1.17.3" %}
{%set hash_type = "sha256" %}
{%set hash_val = "eeec36063467636172c9638ae670601e6e6d63feb974d5192e886327c8735c23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pycrypto >=2.1,!=2.4,<3.0
    - ecdsa >=0.11,<2.0

  run:
    - python
    - pycrypto >=2.1,!=2.4,<3.0
    - ecdsa >=0.11,<2.0

test:
  imports:
    - paramiko

about:
  home: http://www.paramiko.org/
  home: https://github.com/paramiko/paramiko/
  license: LGPL 2.1
  license_file: LICENSE
  summary: 'SSH2 protocol library'
  license_family: LGPL
  dev_url: https://github.com/paramiko/paramiko/
  doc_url: http://docs.paramiko.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - vamega
    - jakirkham
