{% set name = "paramiko" %}
{% set version = "3.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "ad11e540da4f55cedda52931f1a3f812a8238a7af7f62a60de538cd80bb28124" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - bcrypt >=3.2
    - cryptography >=3.3
    - pynacl >=1.5
  run_constrained:
    - pyasn1 >=0.1.7
    - gssapi >=1.4.1   # [not win]
    - pywin32 >=218  # [win]
    - invoke >=2.0

test:
  imports:
    - paramiko
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.paramiko.org/
  license_file: LICENSE
  license: LGPL-2.1-or-later
  summary: SSH2 protocol library
  description: |
    A Python implementation of SSHv2
  license_family: LGPL
  dev_url: https://github.com/paramiko/paramiko/
  doc_url: https://docs.paramiko.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - vamega
    - jakirkham
    - tschoonj
