travis:
  secure:
    BINSTAR_TOKEN: qr34HsxbIHWsxC1Icbvq2weBGLfvibTOxZPD1y76P+ILwRVDJ1g8nyA7GM1eJX3j5ini0w0HDdE8+9VAwdtFgahR8u4mPWcnsskoH6Yc3oIZAGNHJat2z9rlRo1TOY+Qb4UZKJ7ZCZ4piDLRCKH0lXrQcsgYUvxuffUiskuyQ5WyTe1Tb5jPuVOroTbF0TTM6k9PU3FSpDZtsH6BECIrG6JZjEIdpxmhxQYiHNy9yVNkCnsKuIiA5cgm0P/VzKmSDDfgO/OSvsROkb4mwLokksHuMy6A2+1OqzzPAlMyEmcohsE5Exb3Df7er8o5lrpquRnTO6ypETeYGECYeu9e0QbKivZ2iiM3AGZ5wWY0NOx3i0BpTe6ehUww2BpW0yhmhwM3bpGkEKqfPpKWduIhrS8fGZ52d78kB6yMxO1ZxSGRamLTYa8KpUVs4NTZBHCfiBeLyKA7S+YHnnzgZo1UWJ1J3gSeg1jNCARzNSLRzpmthST32PEr2Tc56sCEQhSgCav2THY21P2mOaeJSRrNqaWy7BJn+gAac1evjbEilAznwkJ4VBbUDxjS1lhSrat/fsO1UQequ8VRMh+z/Hf5RNSEy94Hr7qln/Gf8JeG26SRHXMSq4V04euEVUL/Cpt8Wd+VO3bxRdc805hHQA/jJFrQWjsjbiZaP2OlhIRV+Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
