appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: g67wzohrUMJMVO28LzGMAbyIqgp7QLuBhMUuu7vWoXfYj7Jg6XNS/64FyTXJm86UwAcOGD7tAQTZIhycVyihzIPadpt5hrRMGF84haEA4dO1SEut1F4v1CbZy01eZasUfWs4TykD6KWVLaA1MGhDnLK36jOcX8gF6tAqElYZwhF0/kH12k8jXPnIC6Txv/fte2Hpk2xmfYEcN0AVgx26dQLHXlR/grnualtqU1Mu2TiZArYzU+KCRaCcixP7DelOYJ912+R4JzC/p4XbrGhK/UmSvd9D1O6hUkZXDj8kdT0fdn+3wVtSIvUKYRNpmu335Lw0jMDP4jPwfAoICHL76dCA2XcZHoYp8RimUO+Ri2m+w43Eum4E247xb1yMFgC1sTnePaBb1fwzY5tpE5dhuUM+5UwqB+yFMNR8yeFOacTbALw00r2Y66JhUaxyv8altRtraihZGLmWYRqU8J/gmSv4gfCJNqEdh81vvn5CGmBoPvD6nZIpTNAUIcFlxBEzZ46rHEW+JVFfUtZjnk5WEvcZpRytdj7reCJPZEejehA0Vbw6YCSw1tdkWKdtFlSABgcd2gkjB6umalFfQZ5EFD0Pt1/V390lDEDhx7hGka3O3ywqLQWuaQfBjTrmJAmLUMAiEsNYnLH3pqXlYcDZWFNXDyoPkUjgvTMamKy4+2I=}
provider:
  win: azure
